In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

arr  =np.array([1,2,3])
arr2 = np.array([1,2,3], dtype='f') # numpy array 만들기

print(arr, arr.shape, arr.ndim)

arr3 = np.array([[1,2,3],[4,5,6]]) #  2행 3열
print(arr3.shape, arr3.ndim) 

arr3.shape = (3, 2) # 원본 배열 모양 변경
print(arr3)
print(arr3.reshape(1,6)) # 변경된 새로운 배열을 반환 (원본 변경x)

[1 2 3] (3,) 1
(2, 3) 2
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [4]:
arr4 = np.ones([3,5], dtype=int) # 각 값이 1인 5행 3열 배열 만들기 
print(arr4)
print("------------------------")

arr4 = np.zeros([3,5], dtype=int) # 각 값이 0인 5행 3열 배열 만들기 
print(arr4)
print("------------------------")

arr4 = np.empty([3,5], dtype=int) # 각 값? 0인 5행 3열 배열 만들기 
print(arr4)
print("------------------------")

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------


In [5]:
# numpy arr 생성 함수 

arr5 = range(10, 20, 2)     # 반복자 반환
arr6 = np.arange(10, 20, 2) # 값 목록 반환

print(arr5) # 반복자이기 때문에 반복문으로 각 값을 읽어야함
print(list(arr5))
print(arr6)

range(10, 20, 2)
[10, 12, 14, 16, 18]
[10 12 14 16 18]


In [6]:
# 값을 쪼개어 배열을 생성하는 함수 

arr7 = np.linspace(1.0, 2.0, num=5) # 1.0~2.0 까지 5가지로 쪼개어 만들기
print(arr7)

arr8 = np.linspace(10, 20, 5, endpoint=False)
print(arr8)

arr9 = np.linspace(1, 2, 5, retstep=True)
print(arr9)

[1.   1.25 1.5  1.75 2.  ]
[10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [7]:
# 인덱싱과 슬라이싱

arr10 = np.arange(10)
sRule = slice(2,7,2) # 슬라이싱 규칙 만들기 (2에서 7까지 2씩 증가)
print(arr10)
print(arr10[sRule])
print(arr10[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]


In [25]:
# 넘파이에서의 인덱싱과 슬라이싱 차이

pyList = [ [1,2,3], [4,5,6], [7,8,9] ]
npyArr = np.array(pyList)

print(pyList)
print(npyArr)

# 1차원에서 인덱싱과 슬라이싱
print("--------1차원 인덱싱----------")
print(pyList[0])
print(npyArr[0])
print("--------1차원 슬라이싱----------")
print(pyList[:2])
print(npyArr[:2])


# 2차원 이상에서 인덱싱과 슬라이싱
print("--------2차원 인덱싱----------")
print(pyList[0][0])
print(npyArr[0, 0])
print("--------2차원 슬라이싱----------")
print(pyList[0][:2])
print(npyArr[0, :2])
print("--------2차원 슬라이싱 2--------")
print(pyList[:2][:2])
print(npyArr[:2, :2])

print("------------------------------")
print(pyList[:2][:2])
print(npyArr[:2][:2])



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------1차원 인덱싱----------
[1, 2, 3]
[1 2 3]
--------1차원 슬라이싱----------
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
--------2차원 인덱싱----------
1
1
--------2차원 슬라이싱----------
[1, 2]
[1 2]
--------2차원 슬라이싱 2--------
[[1, 2, 3], [4, 5, 6]]
[[1 2]
 [4 5]]
------------------------------
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 인덱싱과 슬라이싱 3

arr = np.array([ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ])

print(arr)

print("----------- 5보다 큰 값 -----------")
print(arr> 5) 
print(arr[arr > 5]) # 각 값의 위치에 TRUE, FALSE를 기준으로 TRUE인 값만 뽑아내기

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------- 5보다 큰 값 -----------
[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11 12]


In [36]:
arr = np.array([np.nan, 1, 2, np.nan,3, 4, 5]) # nan : 결측치
print(arr)
print(np.isnan(arr)) # nan이면 Ture 아니면 False
print(arr[~np.isnan(arr)]) # 결측치를 제외하고 출력 (~는 Not연산)
print( np.isfinite(arr))   # nan, inf 이면 False 아니면 True 
print( arr[np.isfinite(arr)]) 

[nan  1.  2. nan  3.  4.  5.]
[ True False False  True False False False]
[1. 2. 3. 4. 5.]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [62]:
# numpy array의 연산자

arr11 = np.array([1,2,3,4])
arr12 = np.array([10,20,30,40])

print("-------------합연산----------------------")
print(arr12," + ", arr11, " = ", end="")
print(arr12+arr11)
print("------------뺴기연산---------------------")
print(arr12," - ", arr11, " = ", end="")
print(arr12-arr11)
print("-------------곱연산----------------------")
print(arr12," x ", arr11, " = ", end="")
print(arr12*arr11)
print("------------나눗셈연산-------------------")
print(arr12," / ", arr11, " = ", end="")
print(arr12/arr11)

-------------합연산----------------------
[10 20 30 40]  +  [1 2 3 4]  = [11 22 33 44]
------------뺴기연산---------------------
[10 20 30 40]  -  [1 2 3 4]  = [ 9 18 27 36]
-------------곱연산----------------------
[10 20 30 40]  x  [1 2 3 4]  = [ 10  40  90 160]
------------나눗셈연산-------------------
[10 20 30 40]  /  [1 2 3 4]  = [10. 10. 10. 10.]


In [79]:
# 브로드캐스팅
arr13 = np.array([ [0,0,0], [1,1,1], [2,2,2], [3,3,3]])
arr14 = np.array([1,2,3])

print("[ [0,0,0], [1,1,1], [2,2,2], [3,3,3] ] + [1,2,3] = ")
print("---------------------------")
for v in arr13:
    print(v, "+", arr14,"=", arr14+v)

print("---------------------------")

print(arr13+arr14)

[ [0,0,0], [1,1,1], [2,2,2], [3,3,3] ] + [1,2,3] = 
---------------------------
[0 0 0] + [1 2 3] = [1 2 3]
[1 1 1] + [1 2 3] = [2 3 4]
[2 2 2] + [1 2 3] = [3 4 5]
[3 3 3] + [1 2 3] = [4 5 6]
---------------------------
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [101]:
arr15 = np.arange(0,24,2)
arr15 = arr15.reshape(3,4)

print(arr15)

print("------------------------------")
for v in np.nditer(arr15): # 2차원 배열을 1차원 처럼 순회
    print(v, end=" ")
print()

print("------------------------------")
print("size = ", arr15.size) # 모든 요소의 갯수
for v in arr15.reshape(arr15.size):
    print(v, end=" ")


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
------------------------------
0 2 4 6 8 10 12 14 16 18 20 22 
------------------------------
size =  12
0 2 4 6 8 10 12 14 16 18 20 22 

In [ ]:
# 하나의 numpy array는 같은 자료형의 데이터만 저장 가능

arr16 = np.array([1, 2, 3, 4, 5, "hello"])

print(arr16) # 자동 형변환 



['1' '2' '3' '4' '5' 'hello']
